version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres:/var/lib/postgresql/data
  asset-service:
    build:
      context: .
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    env_file:
      - .env