server:
  port: ${PORT:8082}

spring:
  servlet:
    multipart:
      max-file-size: 5MB
  application:
    name: asset-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_AUTHORITY:http://localhost:8080/realms/elykp}
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8080/realms/elykp/protocol/openid-connect/certs}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/elykp_asset_dev}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:040799}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dbo
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/elykp_asset_dev}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:040799}
    default-schema: dbo
    baseline-on-migrate: false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        jdbc:
          '[time_zone]': UTC
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

web:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}

oauth:
  scope: ${SCOPE:SCOPE_asset-service}

cloudinary:
  key: ${CLOUDINARY_API_KEY:789143575217113}
  secret: ${CLOUDINARY_API_SECRET:7dm3F5Xtb2m4ZZofdwjkNHPMRXY}
  cloudname: ${CLOUDINARY_CLOUD_NAME:dig00csrc}
  upload-preset: ${CLOUDINARY_UPLOAD_PRESET:elykp_dev}


storage:
  location: .temp

queue:
  name: image-process-queue
